"""Memory -> Markdown skill files.

README Roadmap item 4: *"Memory sebagai file skill Markdown yang bisa dikonsumsi
Claude Code / Codex langsung, sehingga hasil eksplorasi langsung menjadi
instruksi agent."*

The export is strictly one-directional and derived:

    verified lessons  ->  SKILL.md / CLAUDE.md

Rules enforced here:

* Only **active, verified** lessons are exported. Deprecated (superseded) rules
  are dropped, so rolling back a bad learned rule also removes it from the
  generated skill file.
* Lessons are grouped by knowledge key and ordered by confidence, so the most
  reliable instruction is read first.
* The header pins the memory revision and lesson count, making the generated
  file traceable to the exact state that produced it.
* Content is secret-scanned before it is written: a lesson that somehow carried
  a credential-shaped string fails the export instead of leaking it.
* Export never writes into the project's own `SKILLS.md`; it writes
  `SKILL.md` / `CLAUDE.md`, which are the self-editable files the RAO loop may
  rewrite (see `rsi/risk.py`).
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Iterable, Sequence

from .memory import PersistentMemory
from .sandbox import assert_no_secrets, redact
from .types import Lesson

SKILL_FILE = "SKILL.md"
CLAUDE_FILE = "CLAUDE.md"


def _group_by_key(lessons: Iterable[Lesson]) -> dict[str, list[Lesson]]:
    grouped: dict[str, list[Lesson]] = {}
    for lesson in lessons:
        for key in lesson.knowledge_keys:
            grouped.setdefault(key, []).append(lesson)
    return grouped


def render_skill_markdown(
    memory: PersistentMemory,
    *,
    title: str = "RSI Agent — verified lessons",
    revision: str | None = None,
    generated_at: float | None = None,
) -> str:
    """Render the active, verified lessons as an agent-consumable skill file."""
    lessons = [
        lesson for lesson in memory.active()
        if lesson.verified and not lesson.deprecated
    ]
    revision = revision or memory.revision()
    stamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(generated_at or time.time()))

    lines = [
        "---",
        f"name: rsi-verified-lessons",
        f"description: Verified procedures and boundary conditions mined from "
        f"real execution by the RSI prototype.",
        f"metadata:",
        f"  memory_revision: {revision}",
        f"  lesson_count: {len(lessons)}",
        f"  generated_at: {stamp}",
        f"  source: runs/memory.json (active + verified lessons only)",
        "---",
        "",
        f"# {title}",
        "",
        f"_Memory revision `{revision}` · {len(lessons)} verified lesson(s)._",
        "",
        "These instructions were observed against real execution by the Verifier, "
        "not asserted by the Actor. Apply them as procedures; treat the boundary "
        "sections as things to probe before declaring work done.",
        "",
    ]

    grouped = _group_by_key(lessons)
    for key in sorted(grouped):
        entries = sorted(grouped[key], key=lambda l: (-l.confidence, l.id))
        lines.append(f"## {key}")
        lines.append("")
        for lesson in entries:
            marker = "procedure" if lesson.kind == "procedure" else lesson.kind
            lines.append(
                f"- **[{marker} · conf {lesson.confidence:.2f}]** "
                f"{lesson.content}"
            )
        lines.append("")

    lines += [
        "## How this file is produced",
        "",
        "1. The Actor runs a task inside the ReAct harness.",
        "2. The Verifier grades the attempt against real checks and extracts a "
        "lesson.",
        "3. The improvement loop packages that lesson as a proposal, evaluates "
        "it in isolation against the frozen holdout, and only applies it if the "
        "target metric improves with no critical regression.",
        "4. This file is rendered from the resulting memory. It is a derived "
        "artifact: deleting it loses nothing, and it never feeds back into "
        "memory.",
        "",
    ]
    return "\n".join(lines)


def render_claude_markdown(memory: PersistentMemory, *, revision: str | None = None) -> str:
    """A short CLAUDE.md fragment that points at the generated skill file."""
    revision = revision or memory.revision()
    lessons = [l for l in memory.active() if l.verified]
    keys = sorted(memory.keys())
    return "\n".join([
        "# CLAUDE.md — generated by the RSI prototype",
        "",
        f"_Memory revision `{revision}` · {len(lessons)} verified lesson(s) · "
        f"{len(keys)} knowledge keys._",
        "",
        "Before starting work, read `SKILL.md` in this directory: it contains the "
        "procedures and boundary conditions this agent has verified against real "
        "execution.",
        "",
        "Knowledge keys currently covered: " + (", ".join(keys) or "(none)"),
        "",
        "This file is generated. Do not hand-edit it; change the memory instead "
        "(`runs/memory.json`) and re-run `python -m rsi.cli skills`.",
        "",
    ])


def export_skills(
    memory: PersistentMemory,
    out_dir: str | Path,
    *,
    archive_previous: bool = True,
) -> dict[str, Path]:
    """Write SKILL.md and CLAUDE.md from the current memory.

    When `archive_previous` is set, any existing file is first copied to
    `<name>.<revision>.prev.md` so the previous instruction set stays
    recoverable (ROLLBACK.md).
    """
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}

    skill_md = render_skill_markdown(memory)
    claude_md = render_claude_markdown(memory)
    assert_no_secrets(skill_md, what="SKILL.md")
    assert_no_secrets(claude_md, what="CLAUDE.md")

    for filename, content in ((SKILL_FILE, skill_md), (CLAUDE_FILE, claude_md)):
        target = directory / filename
        if archive_previous and target.exists():
            previous = redact(target.read_text(encoding="utf-8"))
            archive = directory / f"{filename}.{memory.revision()}.prev.md"
            archive.write_text(previous, encoding="utf-8")
        target.write_text(content, encoding="utf-8")
        written[filename] = target
    return written


def skill_stats(memory: PersistentMemory) -> dict[str, Any]:
    lessons = [l for l in memory.active() if l.verified]
    return {
        "memory_revision": memory.revision(),
        "exported_lessons": len(lessons),
        "knowledge_keys": len(memory.keys()),
        "deprecated_excluded": len(memory.entries()) - len(memory.active()),
    }
