/**
 * server/db/columns — the column primitives shared by the DDL.
 *
 * These are FACTORIES, not shared instances: a Drizzle column builder is bound
 * to one table and one column name, so every table needs its own instance.
 * Factories keep DATA_MODEL.md conventions (uuid v7 PKs, `timestamptz` UTC,
 * server-stamped `created_at`/`updated_at`, `citext` email) stated once instead
 * of copy-pasted 20 times — the convention itself is DATA_MODEL.md lines 5–11.
 *
 * Authority: DATA_MODEL.md §1–19. Requirements: NFR-DATA-001 (integrity),
 * NFR-DATA-006 (UTC timestamps), NFR-SEC-012 (audit immutability).
 * Tasks: T-FOUND-005 (schema DDL), T-FOUND-006 (initial migration).
 *
 * Invariants (each is a T-FOUND-005 edge case, verified by INT-DB-001):
 * - `uuidV7PrimaryKey` → `DEFAULT uuidv7()`, i.e. time-ordered ids generated by
 *   the DATABASE, so every writer (repository, seed harness, ops script) gets
 *   a v7 id without remembering to ask for one. `uuidv7()` is a PostgreSQL 18
 *   built-in and is VOLATILE, which is why it is legal in a DEFAULT clause;
 *   the migration refuses to run on an older server (ADR-002 Option B
 *   contingency is a documented, deliberate error, not a silent v4 fallback).
 * - `citextColumn` → `citext`, so `WHERE email = …` is case-insensitive
 *   without a `lower()` wrapper at every call site (DATA_MODEL §1).
 * - `exactNumeric(p, s)` → `numeric(p, s)`, so 10.5 chapter numbers and 1.25
 *   zoom defaults are stored exactly (no float drift) and read back as
 *   STRINGS — the Drizzle contract for `numeric`; repositories map to DTOs
 *   (data-flow.md §7, ADR-003 R2).
 */

import { sql } from 'drizzle-orm';
import { customType, numeric, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * `citext` — case-insensitive text (DATA_MODEL §1 `email citext NOT NULL`).
 *
 * Drizzle 0.45 has no first-class `citext` builder, so the type is declared as
 * a custom type whose DDL spelling is exactly `citext`. The extension itself is
 * created by the initial migration (T-FOUND-006) before any table that uses it.
 */
export const citextColumn = customType<{ data: string; driverData: string }>({
  dataType: () => 'citext',
});

/** The `uuidv7()` DEFAULT expression, shared by every uuid primary key. */
const UUID_V7_DEFAULT = sql`uuidv7()`;

/**
 * uuid v7 primary key (DATA_MODEL line 6: "IDs: `uuid` v7 (time-ordered) PKs
 * unless noted"). The only exception is `audit_event.id` (bigserial, §18).
 *
 * `.primaryKey()` is part of this factory, not of each call site: without it
 * the column is merely `NOT NULL`, PostgreSQL accepts a table with no primary
 * key, and every foreign key that references it fails at migration time with
 * "there is no unique constraint matching given keys" (INT-DB-001 caught this).
 */
export function uuidV7PrimaryKey(name = 'id') {
  return uuid(name).notNull().default(UUID_V7_DEFAULT).primaryKey();
}

/** A nullable uuid FK column (used by the `SET NULL` auditability columns). */
export function uuidReference(name: string) {
  return uuid(name);
}

/** `timestamptz` in UTC — NFR-DATA-006 mandates a single timezone-free shape. */
export function timestamptz(name: string) {
  return timestamp(name, { withTimezone: true, mode: 'date' });
}

/** `created_at` — DATA_MODEL line 7: "every table with lifecycle has created_at". */
export function createdAt() {
  return timestamptz('created_at').notNull().defaultNow();
}

/**
 * `updated_at` — DATA_MODEL line 7: "mutable rows add updated_at".
 *
 * DEFAULT now() because the model gives no application-side stamping contract
 * for it; `reading_progress.updated_at` is the exception that matters and
 * NFR-DATA-003 gives that one an explicit server-stamp rule (LWW).
 */
export function updatedAt() {
  return timestamptz('updated_at').notNull().defaultNow();
}

/** `deleted_at` — soft-delete marker for catalog content (NFR-DATA-002). */
export function deletedAt() {
  return timestamptz('deleted_at');
}

/**
 * Exact fixed-point number, e.g. `exactNumeric('number', 8, 2)` for
 * `numeric(8,2)` chapter numbers (DATA_MODEL §9 — 10.5 must be representable).
 *
 * Returns a string in TypeScript on purpose: `numeric` is arbitrary-precision
 * and converting it to a JS number at the driver boundary is exactly the drift
 * ADR-003 R2 warns about. Repositories narrow/convert deliberately.
 */
export function exactNumeric(name: string, precision: number, scale: number) {
  return numeric(name, { precision, scale });
}
