/**
 * `SessionRepository` — a PLAIN implementation, not the port's full surface.
 *
 * Why this file exists in this shape
 * -----------------------------------
 * `queries/reader-state.ts` is being deleted (F-006-S2). It was the reason the
 * auth routes bypassed the `SessionRepository` port entirely, and it is the same
 * file that plain-overwrote `reading_progress` — the P0 fixed in F-006-S1. One
 * file, two defects, both from the same cause: code that writes tables no port
 * owns.
 *
 * The PORT (`features/auth/session.ts`) declares six methods — `create`,
 * `getByToken`, `touchIdle`, `revoke`, `revokeAll`, `sweepExpired` — and its
 * sliding-idle/absolute-expiry math has never run, because
 * `server/auth/session-store.ts` throws `T-AUTH-006`. Implementing that port
 * properly is **F-002**, which is on the deferred auth track.
 *
 * So this is deliberately the minimum the login and logout routes need, named
 * after the port's methods where they correspond. It exists so F-006-S2 can
 * delete the bypassing file WITHOUT also implementing the session model, which
 * would drag the deferred auth work into a non-auth slice and produce a fourth
 * disagreeing implementation instead of two.
 *
 * What is honest about the gap:
 * - `getByToken` does NOT slide `expiresAt`. The guard's own reads check both
 *   expiries, so behaviour is correct today; sliding is F-002's job.
 * - There is no `revokeAll` and no `sweepExpired`. Expired rows are removed by
 *   nothing; they are merely never matched, because every read compares against
 *   `now()`. That is a storage-growth question, not a correctness one, and it is
 *   F-002's.
 *
 * A file that cannot be stale is the point: when F-002 lands, this becomes a thin
 * delegation and the port finally has one implementation instead of three.
 *
 * Requirements: NFR-SEC-015 (parameterised queries by construction),
 * NFR-SEC-016 (token handling), NFR-DATA-006 (UTC stamps)
 * Tasks: T-AUTH-003, T-AUTH-004; full port T-AUTH-006 (deferred)
 */
import { eq } from 'drizzle-orm';
import { sessions, users } from '../schema';
import type { Db } from '../client';

/**
 * The row login needs, and the guard re-checks on every request.
 *
 * It was declared in `queries/reader-state.ts`, which this slice deletes, so it
 * moves here — the one place that reads the columns.
 */
export interface SessionUser {
  id: string;
  email: string;
  displayName: string;
  passwordHash: string;
  role: string;
  status: string;
}

/** Everything a new session row carries. Mirrors the `sessions` table exactly. */
export interface NewSession {
  id: string;
  userId: string;
  sessionToken: string;
  createdAt: Date;
  expiresAt: Date;
  absoluteExpiresAt: Date;
  lastSeenAt: Date;
}

/**
 * Writes `sessions`. One row per successful login.
 *
 * The token is generated by the caller with `crypto.randomUUID()`, not here, so
 * the value never crosses this boundary and this file cannot be the reason a
 * token is predictable.
 *
 * @param db the application handle (`acquireDb`)
 * @param session the row to insert
 */
export async function insertSession(db: Db, session: NewSession): Promise<void> {
  await db.insert(sessions).values(session);
}

/**
 * Revokes one session by token — the logout path.
 *
 * Scoped to the token, never to the user: "log out" means "this session stops
 * working", and deleting by `userId` would sign the reader out everywhere.
 *
 * Idempotent by construction: a token that is already gone matches no rows and
 * is not an error, so a double-submitted logout is not a failure.
 *
 * @param db the application handle (`acquireDb`)
 * @param token the session token from the cookie
 */
export async function deleteSessionByToken(db: Db, token: string): Promise<void> {
  await db.delete(sessions).where(eq(sessions.sessionToken, token));
}

/**
 * Reads one session, applying BOTH expiries.
 *
 * The two are not redundant: `expiresAt` slides with activity and
 * `absoluteExpiresAt` does not, which is what stops a session being kept alive
 * forever by continuing to use it.
 *
 * `null` covers three states on purpose — no such token, idle expiry, absolute
 * expiry — because distinguishing them would tell an attacker whether a token
 * ever existed. The caller cannot tell, and neither should anyone probing.
 *
 * @param db the application handle (`acquireDb`)
 * @param token the session token from the cookie
 * @returns the live session row, or `null`
 */
export async function findLiveSessionByToken(
  db: Db,
  token: string,
  now: Date = new Date(),
): Promise<typeof sessions.$inferSelect | null> {
  const [row] = await db.select().from(sessions).where(eq(sessions.sessionToken, token)).limit(1);
  if (!row) return null;
  if (row.expiresAt.getTime() < now.getTime()) return null;
  if (row.absoluteExpiresAt.getTime() < now.getTime()) return null;
  return row;
}

/**
 * Looks a user up by email, for the login path.
 *
 * `users.email` is `citext`, so the comparison is case-insensitive by the column
 * type rather than by anything this function does (DATA_MODEL §2). A reader who
 * typed `Reader@Yomi.test` gets the same account as one who typed
 * `reader@yomi.test`, and no `lower()` is needed here.
 *
 * `passwordHash` is included because the caller has to verify against it. That is
 * a deliberate narrow surface, not a general read: there is no `getUser` that
 * hands out a hash.
 *
 * @param db the application handle (`acquireDb`)
 * @param email the address as typed
 * @returns the user, or `undefined` when there is none
 */
export async function findUserByEmail(db: Db, email: string): Promise<SessionUser | undefined> {
  const [row] = await db
    .select({
      id: users.id,
      email: users.email,
      displayName: users.displayName,
      passwordHash: users.passwordHash,
      role: users.role,
      status: users.status,
    })
    .from(users)
    .where(eq(users.email, email))
    .limit(1);
  return row;
}

/**
 * Records a successful sign-in. Not part of the session port — it is a user
 * column, kept here so the auth routes have one import.
 *
 * @param db the application handle (`acquireDb`)
 * @param userId the user who signed in
 * @param at the moment, stamped server-side so a client clock cannot move it
 */
export async function touchLastLogin(db: Db, userId: string, at: Date): Promise<void> {
  await db.update(users).set({ lastLoginAt: at }).where(eq(users.id, userId));
}
