import type { OpsMapReadModel, OpsMapStall } from "./types";

/**
 * Deterministic pilot snapshot for the operations map (business day 29 Sep 2026,
 * 09:47 WIB, area Jakarta Selatan). Served by GET /api/v1/hq/ops-map with
 * `meta.source = "fixture"` until LocationReports/shift read models are wired
 * (TASKS.md T-LOC-002, T-HQ-001). Positions are operator-reported (ADR-0007).
 */

const D = "2026-09-29";
const t = (hhmmss: string) => `${D}T${hhmmss}+07:00`;

const AS_OF = t("09:47:22");

const stalls: readonly OpsMapStall[] = [
  {
    stallId: "ST-TBT-01", code: "Tebet 01", areaName: "Tebet",
    operator: { shortName: "Rian", fullName: "Rian Pratama", initials: "RP" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2338, lng: 106.8532, reportedAt: t("09:47:02"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 9, placeName: "Jl. Tebet Barat Dalam Raya · depan Taman Honda" },
    sales: { grossMinor: 1_185_000, transactions: 27, expensesMinor: 140_000, operatingSince: t("06:50:00"), lastSaleAt: t("09:42:10") },
    traffic: { band: "RAMAI", label: "Ramai", sampledAt: t("09:15:00"), countPer5Min: 71, trend: "UP", trendVsLabel: "↑ dibanding 08:15" },
    site: { weather: "KERING", weatherLabel: "Kering", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 20, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Teduh, permukaan kering, arus pejalan kaki stabil.", reportedAt: t("09:15:00") },
    sample: { sampleId: "SMP-0912", capturedAt: t("09:15:00"), durationSec: 30, sourceLabel: "Operator mobile", observations: 71, band: "RAMAI", bandLabel: "Ramai", thumbnailUrl: "/hq/samples/tebet-01-0915.jpg", anonymised: true },
    suitability: {
      overall: 84, statusLabel: "Layak Dipertahankan", statusTone: "ok", computedAt: t("09:40:00"), methodLabel: "Dari laporan operator & sampling",
      factors: [
        { key: "traffic", label: "Keramaian", score: 88, sourceLabel: "Sampling 09:15" },
        { key: "weather", label: "Cuaca", score: 82, sourceLabel: "Laporan operator" },
        { key: "shelter", label: "Naungan", score: 76, sourceLabel: "Profil lokasi" },
        { key: "ground", label: "Kondisi permukaan", score: 90, sourceLabel: "Laporan operator" },
        { key: "sales", label: "Penjualan terkini", score: 85, sourceLabel: "Transaksi 60 menit" },
      ],
    },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-TBT-02", code: "Tebet 02", areaName: "Tebet",
    operator: { shortName: "Sari", fullName: "Sari Wulandari", initials: "SW" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2262, lng: 106.8608, reportedAt: t("09:46:20"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 14, placeName: "Jl. Tebet Timur Dalam Raya · dekat pasar" },
    sales: { grossMinor: 890_000, transactions: 21, expensesMinor: 95_000, operatingSince: t("07:10:00"), lastSaleAt: t("09:39:00") },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("09:05:00"), countPer5Min: 38, trend: "FLAT", trendVsLabel: "≈ sama dengan 08:05" },
    site: { weather: "KERING", weatherLabel: "Kering", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 25, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Kondisi normal.", reportedAt: t("09:05:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-KNG-01", code: "Kuningan 01", areaName: "Kuningan",
    operator: { shortName: "Dimas", fullName: "Dimas Anggara", initials: "DA" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2360, lng: 106.8250, reportedAt: t("09:45:40"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 11, placeName: "Jl. Kuningan Barat · depan perkantoran" },
    sales: { grossMinor: 1_020_000, transactions: 24, expensesMinor: 120_000, operatingSince: t("07:00:00"), lastSaleAt: t("09:44:00") },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("09:20:00"), countPer5Min: 45, trend: "FLAT", trendVsLabel: "≈ sama dengan 08:20" },
    site: { weather: "GERIMIS", weatherLabel: "Gerimis", ground: "BASAH", groundLabel: "Basah", rainProbabilityPct: 60, suitabilityLabel: "Cukup", suitabilityTone: "waiting", reason: "Ada kanopi gedung, permukaan sebagian basah.", reportedAt: t("09:20:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-KNG-02", code: "Kuningan 02", areaName: "Kuningan",
    operator: { shortName: "Bayu", fullName: "Bayu Saputra", initials: "BS" },
    state: "attention", statusLabel: "Beroperasi", statusTone: "ok",
    attentionLabel: "Perlu Perhatian", attentionReason: "1 insiden terbuka · lokasi kurang ideal",
    position: { lat: -6.2296, lng: 106.8327, reportedAt: t("09:47:00"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 12, placeName: "Jl. HR Rasuna Said · simpang Jl. Denpasar Raya" },
    sales: { grossMinor: 1_310_000, transactions: 31, expensesMinor: 215_000, operatingSince: t("07:05:00"), lastSaleAt: t("09:45:30") },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("09:32:00"), countPer5Min: 42, trend: "DOWN", trendVsLabel: "↓ dibanding 08:30" },
    site: { weather: "GERIMIS", weatherLabel: "Gerimis", ground: "BASAH", groundLabel: "Basah", rainProbabilityPct: 68, suitabilityLabel: "Kurang Ideal", suitabilityTone: "attention", reason: "Area terbuka dan permukaan mulai basah.", reportedAt: t("09:40:00") },
    sample: { sampleId: "SMP-0932", capturedAt: t("09:32:00"), durationSec: 30, sourceLabel: "Operator mobile", observations: 42, band: "SEDANG", bandLabel: "Sedang", thumbnailUrl: "/hq/samples/kuningan-02-0932.jpg", anonymised: true },
    suitability: {
      overall: 62, statusLabel: "Pertimbangkan Relokasi", statusTone: "attention", computedAt: t("09:40:00"), methodLabel: "Dari laporan operator & sampling",
      factors: [
        { key: "traffic", label: "Keramaian", score: 72, sourceLabel: "Sampling 09:32" },
        { key: "weather", label: "Cuaca", score: 45, sourceLabel: "Laporan operator 09:40" },
        { key: "shelter", label: "Naungan", score: 40, sourceLabel: "Profil lokasi" },
        { key: "ground", label: "Kondisi permukaan", score: 55, sourceLabel: "Laporan operator 09:40" },
        { key: "sales", label: "Penjualan terkini", score: 79, sourceLabel: "Transaksi 60 menit" },
      ],
    },
    security: {
      openCount: 1,
      latest: {
        incidentId: "INC-2026-0929-014", categoryLabel: "Permintaan uang tidak resmi",
        reportedAt: t("09:21:00"), reportedByLabel: "Bayu",
        evidence: { photos: 2, videos: 1 }, amountRecordedMinor: 50_000,
        reviewStatusLabel: "Belum ditinjau", reviewStatusTone: "waiting",
      },
    },
    openIncidents: 1,
  },
  {
    stallId: "ST-CKN-01", code: "Cikini 01", areaName: "Cikini",
    operator: { shortName: "Arif", fullName: "Arif Hidayat", initials: "AH" },
    state: "offline", statusLabel: "Belum Mulai", statusTone: "neutral",
    attentionLabel: "Posisi lama", attentionReason: "Laporan posisi terakhir 36 menit lalu · shift belum dibuka",
    position: { lat: -6.1936, lng: 106.8408, reportedAt: t("09:11:22"), source: "OPERATOR_APP_GPS", reason: "HQ_REQUEST", accuracyM: 25, placeName: "Jl. Cikini Raya · dekat stasiun" },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("08:50:00"), countPer5Min: 33, trend: "FLAT", trendVsLabel: "≈ sama dengan 07:50" },
    site: { weather: "MENDUNG", weatherLabel: "Mendung", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 45, suitabilityLabel: "Cukup", suitabilityTone: "waiting", reason: "Belum ada laporan kondisi hari ini.", reportedAt: t("08:50:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-MGR-01", code: "Manggarai 01", areaName: "Manggarai",
    operator: { shortName: "Yudi", fullName: "Yudi Setiawan", initials: "YS" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2108, lng: 106.8484, reportedAt: t("09:46:37"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 10, placeName: "Jl. Manggarai Utara · pintu stasiun" },
    sales: { grossMinor: 740_000, transactions: 19, expensesMinor: 80_000, operatingSince: t("07:20:00"), lastSaleAt: t("09:41:00") },
    traffic: { band: "RAMAI", label: "Ramai", sampledAt: t("09:25:00"), countPer5Min: 88, trend: "UP", trendVsLabel: "↑ dibanding 08:25" },
    site: { weather: "GERIMIS", weatherLabel: "Gerimis", ground: "BASAH", groundLabel: "Basah", rainProbabilityPct: 65, suitabilityLabel: "Cukup", suitabilityTone: "waiting", reason: "Ramai namun permukaan basah; ada kanopi stasiun.", reportedAt: t("09:25:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-STB-01", code: "Setiabudi 01", areaName: "Setiabudi",
    operator: { shortName: "Nia", fullName: "Nia Ramadhani", initials: "NR" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2142, lng: 106.8278, reportedAt: t("09:45:10"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 16, placeName: "Jl. Setiabudi Tengah · dekat waduk" },
    sales: { grossMinor: 655_000, transactions: 16, expensesMinor: 70_000, operatingSince: t("07:30:00"), lastSaleAt: t("09:38:00") },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("09:10:00"), countPer5Min: 36, trend: "DOWN", trendVsLabel: "↓ dibanding 08:10" },
    site: { weather: "GERIMIS", weatherLabel: "Gerimis", ground: "BASAH", groundLabel: "Basah", rainProbabilityPct: 66, suitabilityLabel: "Cukup", suitabilityTone: "waiting", reason: "Gerimis ringan, ada teras ruko.", reportedAt: t("09:35:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-PSM-01", code: "Pasar Minggu 01", areaName: "Pasar Minggu",
    operator: { shortName: "Agus", fullName: "Agus Santoso", initials: "AS" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2833, lng: 106.8458, reportedAt: t("09:44:15"), source: "OPERATOR_APP_GPS", reason: "MOVE", accuracyM: 8, placeName: "Jl. Raya Pasar Minggu · sisi terminal" },
    sales: { grossMinor: 1_540_000, transactions: 35, expensesMinor: 160_000, operatingSince: t("06:40:00"), lastSaleAt: t("09:46:00") },
    traffic: { band: "RAMAI", label: "Ramai", sampledAt: t("09:12:00"), countPer5Min: 96, trend: "UP", trendVsLabel: "↑ dibanding 08:10" },
    site: { weather: "KERING", weatherLabel: "Kering", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 15, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Pindah 320 m ke sisi terminal karena titik lama penuh.", reportedAt: t("09:12:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-PSM-02", code: "Pasar Minggu 02", areaName: "Pasar Minggu",
    operator: { shortName: "Wawan", fullName: "Wawan Kurnia", initials: "WK" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2792, lng: 106.8402, reportedAt: t("09:43:05"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 13, placeName: "Jl. Pejaten Raya · depan minimarket" },
    sales: { grossMinor: 610_000, transactions: 15, expensesMinor: 60_000, operatingSince: t("07:40:00"), lastSaleAt: t("09:30:00") },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("09:00:00"), countPer5Min: 40, trend: "FLAT", trendVsLabel: "≈ sama dengan 08:00" },
    site: { weather: "KERING", weatherLabel: "Kering", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 15, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Kondisi normal.", reportedAt: t("09:00:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-PCR-01", code: "Pancoran 01", areaName: "Pancoran",
    operator: { shortName: "Hendra", fullName: "Hendra Gunawan", initials: "HG" },
    state: "incident", statusLabel: "Insiden", statusTone: "blocked",
    attentionLabel: "Insiden operasional", attentionReason: "Kompor gerobak tidak menyala · dilaporkan 09:28",
    position: { lat: -6.2416, lng: 106.8446, reportedAt: t("09:45:50"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 10, placeName: "Jl. Raya Pasar Minggu · bawah flyover Pancoran" },
    sales: { grossMinor: 480_000, transactions: 12, expensesMinor: 45_000, operatingSince: t("07:15:00"), lastSaleAt: t("09:26:00") },
    traffic: { band: "RAMAI", label: "Ramai", sampledAt: t("09:02:00"), countPer5Min: 64, trend: "FLAT", trendVsLabel: "≈ sama dengan 08:00" },
    site: { weather: "MENDUNG", weatherLabel: "Mendung", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 40, suitabilityLabel: "Cukup", suitabilityTone: "waiting", reason: "Terlindung flyover; penjualan terhenti karena peralatan.", reportedAt: t("09:28:00") },
    security: { openCount: 0 },
    openIncidents: 1,
  },
  {
    stallId: "ST-MPG-01", code: "Mampang 01", areaName: "Mampang",
    operator: { shortName: "Fajar", fullName: "Fajar Nugroho", initials: "FN" },
    state: "attention", statusLabel: "Beroperasi", statusTone: "ok",
    attentionLabel: "Perlu Perhatian", attentionReason: "Stok siomay menipis (sisa 18 porsi)",
    position: { lat: -6.2472, lng: 106.8268, reportedAt: t("09:44:48"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 12, placeName: "Jl. Mampang Prapatan Raya · depan halte" },
    sales: { grossMinor: 1_105_000, transactions: 26, expensesMinor: 110_000, operatingSince: t("06:55:00"), lastSaleAt: t("09:43:00") },
    traffic: { band: "RAMAI", label: "Ramai", sampledAt: t("09:18:00"), countPer5Min: 69, trend: "UP", trendVsLabel: "↑ dibanding 08:18" },
    site: { weather: "MENDUNG", weatherLabel: "Mendung", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 50, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Halte memberi naungan; arus pejalan kaki tinggi.", reportedAt: t("09:18:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-KLB-01", code: "Kalibata 01", areaName: "Kalibata",
    operator: { shortName: "Lina", fullName: "Lina Marlina", initials: "LM" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2586, lng: 106.8468, reportedAt: t("09:46:05"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 9, placeName: "Jl. Raya Kalibata · dekat stasiun Duren Kalibata" },
    sales: { grossMinor: 830_000, transactions: 20, expensesMinor: 75_000, operatingSince: t("07:00:00"), lastSaleAt: t("09:40:00") },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("09:08:00"), countPer5Min: 47, trend: "UP", trendVsLabel: "↑ dibanding 08:08" },
    site: { weather: "KERING", weatherLabel: "Kering", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 20, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Kondisi normal.", reportedAt: t("09:08:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-MTG-01", code: "Menteng 01", areaName: "Menteng",
    operator: { shortName: "Rosa", fullName: "Rosa Amalia", initials: "RA" },
    state: "offline", statusLabel: "Offline", statusTone: "neutral",
    attentionLabel: "Posisi lama", attentionReason: "Tidak ada laporan posisi 52 menit · aplikasi terakhir online 09:01",
    position: { lat: -6.1978, lng: 106.8302, reportedAt: t("08:55:10"), source: "OPERATOR_APP_GPS", reason: "SHIFT_START", accuracyM: 18, placeName: "Jl. HOS Cokroaminoto · Taman Menteng" },
    sales: { grossMinor: 320_000, transactions: 8, expensesMinor: 40_000, operatingSince: t("07:45:00"), lastSaleAt: t("08:58:00") },
    traffic: { band: "SEPI", label: "Sepi", sampledAt: t("08:40:00"), countPer5Min: 18, trend: "DOWN", trendVsLabel: "↓ dibanding 07:40" },
    site: { weather: "GERIMIS", weatherLabel: "Gerimis", ground: "BASAH", groundLabel: "Basah", rainProbabilityPct: 62, suitabilityLabel: "Kurang Ideal", suitabilityTone: "attention", reason: "Area taman terbuka, gerimis sejak 08:30.", reportedAt: t("08:40:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-SDM-01", code: "Sudirman 01", areaName: "Sudirman",
    operator: { shortName: "Teguh", fullName: "Teguh Prasetyo", initials: "TP" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2241, lng: 106.8097, reportedAt: t("09:46:50"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 7, placeName: "Jl. Jend. Sudirman · SCBD Lot 8" },
    sales: { grossMinor: 1_260_000, transactions: 29, expensesMinor: 130_000, operatingSince: t("06:45:00"), lastSaleAt: t("09:46:00") },
    traffic: { band: "RAMAI", label: "Ramai", sampledAt: t("09:22:00"), countPer5Min: 104, trend: "UP", trendVsLabel: "↑ dibanding 08:22" },
    site: { weather: "MENDUNG", weatherLabel: "Mendung", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 48, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Kanopi gedung, arus pejalan kaki tinggi.", reportedAt: t("09:22:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-SDM-02", code: "Sudirman 02", areaName: "Sudirman",
    operator: { shortName: "Ika", fullName: "Ika Puspita", initials: "IP" },
    state: "normal", statusLabel: "Beroperasi", statusTone: "ok",
    position: { lat: -6.2224, lng: 106.8112, reportedAt: t("09:46:12"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 9, placeName: "Jl. Jend. Sudirman · halte Bendungan Hilir" },
    sales: { grossMinor: 975_000, transactions: 23, expensesMinor: 90_000, operatingSince: t("07:00:00"), lastSaleAt: t("09:45:00") },
    traffic: { band: "RAMAI", label: "Ramai", sampledAt: t("09:24:00"), countPer5Min: 92, trend: "FLAT", trendVsLabel: "≈ sama dengan 08:24" },
    site: { weather: "MENDUNG", weatherLabel: "Mendung", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 48, suitabilityLabel: "Ideal", suitabilityTone: "ok", reason: "Halte memberi naungan.", reportedAt: t("09:24:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
  {
    stallId: "ST-SNY-01", code: "Senayan 01", areaName: "Senayan",
    operator: { shortName: "Bima", fullName: "Bima Aditya", initials: "BA" },
    state: "attention", statusLabel: "Beroperasi", statusTone: "ok",
    attentionLabel: "Perlu Perhatian", attentionReason: "Lokasi dilaporkan padat (3 gerobak lain)",
    position: { lat: -6.2256, lng: 106.8073, reportedAt: t("09:45:30"), source: "OPERATOR_APP_GPS", reason: "PERIODIC_CONFIRM", accuracyM: 11, placeName: "Jl. Asia Afrika · pintu 7 GBK" },
    sales: { grossMinor: 705_000, transactions: 17, expensesMinor: 65_000, operatingSince: t("07:10:00"), lastSaleAt: t("09:37:00") },
    traffic: { band: "SEDANG", label: "Sedang", sampledAt: t("09:16:00"), countPer5Min: 44, trend: "DOWN", trendVsLabel: "↓ dibanding 08:16" },
    site: { weather: "MENDUNG", weatherLabel: "Mendung", ground: "KERING", groundLabel: "Kering", rainProbabilityPct: 45, suitabilityLabel: "Cukup", suitabilityTone: "waiting", reason: "Padat pedagang lain; pertimbangkan pintu 5.", reportedAt: t("09:16:00") },
    security: { openCount: 0 },
    openIncidents: 0,
  },
];

export const opsMapFixture: OpsMapReadModel = {
  businessDay: D,
  asOf: AS_OF,
  computedAt: t("09:47:04"),
  areaLabel: "Jakarta Selatan",
  stalls,
  events: [
    { eventId: "EV-01", kind: "OPERATOR_UPDATE", lat: -6.2308, lng: 106.8314, at: t("09:47:00"), label: "Kuningan 02 mengirim posisi baru", stallCode: "Kuningan 02" },
    { eventId: "EV-02", kind: "TRAFFIC_SAMPLE", lat: -6.2311, lng: 106.8341, at: t("09:32:00"), label: "Sampling keramaian · 42 / 5 menit", stallCode: "Kuningan 02" },
    { eventId: "EV-03", kind: "SECURITY_INCIDENT", lat: -6.2284, lng: 106.8309, at: t("09:21:00"), label: "Insiden keamanan dilaporkan", stallCode: "Kuningan 02" },
    { eventId: "EV-04", kind: "WET_AREA", lat: -6.2218, lng: 106.8296, at: t("09:35:00"), label: "Area basah · laporan Setiabudi 01", stallCode: "Setiabudi 01" },
    { eventId: "EV-05", kind: "WET_AREA", lat: -6.2385, lng: 106.8400, at: t("09:40:00"), label: "Area basah · laporan Kuningan 02", stallCode: "Kuningan 02" },
    { eventId: "EV-06", kind: "TRAFFIC_SAMPLE", lat: -6.2351, lng: 106.8547, at: t("09:15:00"), label: "Sampling keramaian · 71 / 5 menit", stallCode: "Tebet 01" },
    { eventId: "EV-07", kind: "RELOCATION", lat: -6.2833, lng: 106.8458, from: { lat: -6.2812, lng: 106.8433 }, at: t("09:10:00"), label: "Pasar Minggu 01 berpindah 320 m", stallCode: "Pasar Minggu 01" },
    { eventId: "EV-08", kind: "OPERATOR_UPDATE", lat: -6.2121, lng: 106.8497, at: t("09:46:37"), label: "Manggarai 01 konfirmasi posisi", stallCode: "Manggarai 01" },
    { eventId: "EV-09", kind: "TRAFFIC_SAMPLE", lat: -6.2255, lng: 106.8118, at: t("09:24:00"), label: "Sampling keramaian · 92 / 5 menit", stallCode: "Sudirman 02" },
    { eventId: "EV-10", kind: "WET_AREA", lat: -6.2088, lng: 106.8462, at: t("09:25:00"), label: "Area basah · laporan Manggarai 01", stallCode: "Manggarai 01" },
  ],
  activity: [
    { activityId: "ACT-01", at: t("09:47:00"), stallCode: "Kuningan 02", kind: "POSITION", text: "Kuningan 02 mengirim posisi baru" },
    { activityId: "ACT-02", at: t("09:42:10"), stallCode: "Tebet 01", kind: "SALE", text: "Tebet 01 — transaksi Rp 85.000" },
    { activityId: "ACT-03", at: t("09:32:00"), stallCode: "Kuningan 02", kind: "SAMPLE", text: "Kuningan 02 — sampling keramaian baru" },
    { activityId: "ACT-04", at: t("09:21:00"), stallCode: "Kuningan 02", kind: "INCIDENT", text: "Kuningan 02 — insiden keamanan dilaporkan" },
    { activityId: "ACT-05", at: t("09:10:00"), stallCode: "Pasar Minggu 01", kind: "MOVE", text: "Pasar Minggu 01 — berpindah 320 m" },
  ],
  weatherZones: [
    { zoneId: "WZ-01", lat: -6.2215, lng: 106.8335, radiusM: 2100, label: "Gerimis · laporan 4 operator", at: t("09:40:00") },
  ],
};
