// HomeOps — root layout (T-PLAT-002, docs/design/PAGES.md).
//
// Loads design tokens (globals.css), sets the document language and viewport, and renders nothing
// else: no layout may fetch household data, because each page loads exactly what it renders
// (ARCHITECTURE.md §8, PERFORMANCE.md PB-S1).

import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import './globals.css';
import { STRINGS } from '../shared/strings/en';

export const metadata: Metadata = {
  title: { default: STRINGS.app.name, template: `%s · ${STRINGS.app.name}` },
  description: STRINGS.app.tagline,
  // A household app is never embedded and never indexed (PRIVACY.md §1, SECURITY.md §7).
  robots: { index: false, follow: false },
  // The PWA manifest is generated by src/app/manifest.ts in VS-15 (ADR-014 §33, T-PWA-001).
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Members may zoom to 200% and the layout must stay usable (NFR-A11Y-004).
  maximumScale: 5,
  userScalable: true,
  // No `themeColor` yet: ADR-014 §33 requires the browser-chrome and manifest colours to come from
  // the design tokens, and T-PLAT-015 forbids a colour literal outside globals.css. T-PWA-001 adds
  // both, derived from `--color-bg` per theme, instead of inventing a hex value here.
};

export default function RootLayout({ children }: { readonly children: ReactNode }) {
  return (
    // Language is English in v1; a locale bundle is added to src/shared/strings without touching
    // components (DESIGN.md §17 T-7, PRD §2).
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
